dataset: fiqa
split: test

model: sentence-transformers/all-MiniLM-L6-v2
query_prompt: query
passage_prompt: document
max_length: 512

top_k: 1000

batch_size: 128
corpus_chunk_size: 50000

out_dir: "results"
save_runfile: true
