dataset: trec-covid
split: test

provider: hf_auto
model: BAAI/bge-large-en-v1.5
query_prompt: query
passage_prompt: passage
max_length: 512
pooling: mean # mean | cls
normalize_embeddings: true
dtype: auto # auto | float32 | float16 | bfloat16

top_k: 1000
batch_size: 128
corpus_chunk_size: 50000
max_queries: null

out_dir: results
save_runfile: true
print_topk: 0