seed: 42
output: results/trec_covid_bm25_grid.csv

beir:
  dataset: trec-covid
  split: test

pyserini:
  prebuilt_index: beir-v1.0.0-trec-covid.flat

retrieval:
  k: 1000

search:
  k1: [0, 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3]
  b:  [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
